# Generated by Django 4.1.4 on 2022-12-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_language_snippet_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='lineous',
            new_name='linenos',
        ),
    ]
